### ISSUE TITLE
Hi :)

### ISSUE THREAD

**Issue by JohnLonginotto** [llrs/Hmmer_parser#1]
Hi! I read a post of yours on Reproducibility in Bioinformatics on StackExchange and I would like to talk to you about a project im working on called log.bio

It's all python, and it works (im using it right now), but I need some help. Since you're also a Bioinformatician / Python Programmer, I was wondering if you'd like to work on it with me? No stress if you don't. Just thought it might interest you after reading your post.

Also I dont know how to send messages directly to people on either SE or GitHub, which is why i've made an issue, hahah, hope that's not too rude of me :)

**Comment by llrs** [comment]
Hi John,

Interesting project, I like the idea of representing the commands in directed acycled graphs to relate them. As well as classify them between objects/data and events/commands!

So I will try to participate (don't expect much, just refactoring and moving to python 3.4 at most) or anything you wish, though I don't expect to have much free time (for free coding) until July.

This has been a better way to reach me, you got my attention ;)
